/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import tenantSelect from "../../src/plugins/tenant-select/./strapi-admin.ts";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "tenant-select": tenantSelect,
  },
});
